"""4

Revision ID: 8cf683982f2f
Revises: e6b213c0a263
Create Date: 2023-07-25 12:26:10.267273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf683982f2f'
down_revision = 'e6b213c0a263'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
