"""last rev

Revision ID: a06f8046055a
Revises: 8cf683982f2f
Create Date: 2023-07-26 11:00:42.204293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a06f8046055a'
down_revision = '8cf683982f2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'status')
    # ### end Alembic commands ###
