"""ll

Revision ID: ea640a9fb307
Revises: a06f8046055a
Create Date: 2023-07-26 11:07:19.635319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea640a9fb307'
down_revision = 'a06f8046055a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
